export const AVERAGE_LISTING = "AVERAGE_LISTING";

export const MOSTCONTACTED_LISTING = "MOSTCONTACTED_LISTING";

export const AUTHORS_LIST = "AUTHORS_LIST";

export const TOPFIVEPERMONTH_LIST = "TOPFIVEPERMONTH_LIST";

